name: GHA Docs

on:
  push:
    branches:
      - test

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get docs commits
      id: docs_commits
      run: |
        logs=$(git log origin/main..HEAD --format='- %s by %an on %ci (%h)' --grep='^docs')
        if [ -n "$logs" ]; then
          { head -n 5 Changelog.md; echo -e "\n## $(date +'%Y-%m-%d')\n$logs\n"; tail -n +6 Changelog.md; } > Changelog.tmp
          mv Changelog.tmp Changelog.md
          cat Changelog.md
        fi
        
